/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "rgb(var(--color-background) / <alpha-value>)",
        surface: "rgb(var(--color-surface) / <alpha-value>)",
        "surface-subtle": "rgb(var(--color-surface-subtle) / <alpha-value>)",
        "surface-elevated": "rgb(var(--color-surface-elevated) / <alpha-value>)",
        "brand-surface": "rgb(var(--color-brand-surface) / <alpha-value>)",
        "text-primary": "rgb(var(--color-text-primary) / <alpha-value>)",
        "text-secondary": "rgb(var(--color-text-secondary) / <alpha-value>)",
        "text-muted": "rgb(var(--color-text-muted) / <alpha-value>)",
        "text-inverse": "rgb(var(--color-text-inverse) / <alpha-value>)",
        "border-subtle": "rgb(var(--color-border-subtle) / <alpha-value>)",
        "border-default": "rgb(var(--color-border-default) / <alpha-value>)",
        "border-strong": "rgb(var(--color-border-strong) / <alpha-value>)",
        accent: "rgb(var(--color-accent) / <alpha-value>)",
        "accent-hover": "rgb(var(--color-accent-hover) / <alpha-value>)",
        "accent-strong": "rgb(var(--color-accent-strong) / <alpha-value>)",
        "accent-subtle": "rgb(var(--color-accent-subtle) / <alpha-value>)",
        "accent-border": "rgb(var(--color-accent-border) / <alpha-value>)",
        focus: "rgb(var(--color-focus) / <alpha-value>)",
        success: "rgb(var(--color-success) / <alpha-value>)",
        error: "rgb(var(--color-error) / <alpha-value>)",
        overlay: "rgb(var(--color-overlay) / <alpha-value>)",
        /* Transitional aliases: remove after all downstream consumers migrate. */
        "bdigital-navy": "#0a1f3e",
        "bdigital-dark-navy": "#07172a",
        "bdigital-midnight": "#0b2236",
        "bdigital-night": "#122a40",
        "bdigital-cyan": "#06b6d4",
        "bdigital-cyan-light": "#22d3ee",
        "bdigital-cyan-dark": "#0e7490",
        "neutral-gray": "#6b7280",
      },
    },
  },
  plugins: [],
};
