import { buildContactRequest, buildConsultationRequest, buildServiceInquiryRequest, LANGUAGES, LeadContractError } from "../src/api/leadContract";
import { LeadSubmissionError, submitLeadTo } from "../src/utils/leadSubmission";
const equal=(a:unknown,b:unknown)=>{if(a!==b)throw new Error(`Expected ${String(b)}, received ${String(a)}`)};
const rejects=async(fn:()=>unknown,check:(e:unknown)=>boolean)=>{try{await fn()}catch(e){if(check(e))return;throw e}throw new Error("Expected rejection")};
const consultation={fullName:" Ada ",email:"ada@example.com",phone:"",company:"Dial",website:"https://example.com",businessType:"startup",currentChallenges:"Challenge",goals:"Growth",interestedServices:["web"],preferredContact:"video",preferredTime:"",additionalInfo:"",newsletter:false};
const inquiry={fullName:" Ada ",email:"ada@example.com",phone:"",company:"Dial",website:"",selectedService:"Web",selectedPackage:"Starter",projectTypes:["new-website"],currentSituation:"Now",projectGoals:"Grow",targetAudience:"",timeline:"asap",budget:"discuss",additionalServices:["SEO"],preferredContact:"email",additionalInfo:"",howDidYouHear:"",newsletter:false};
for(const language of LANGUAGES){equal(buildContactRequest({name:" Ada ",email:"ada@example.com",message:" Hi ",company:"",phone:"",language}).language,language);equal(buildConsultationRequest({...consultation,language}).fullName,"Ada");equal(buildServiceInquiryRequest({...inquiry,language}).language,language)}
let threw=false;try{buildContactRequest({name:"  ",email:"a@b.co",message:"x",language:"me"})}catch(e){threw=e instanceof LeadContractError}equal(threw,true);
for(const invalid of [{...consultation,language:"en",businessType:"translated",website:"example.com",newsletter:"false"},{...inquiry,language:"fr",projectTypes:Array(21).fill("x"),timeline:"soon",budget:"cheap",newsletter:"indeterminate"}]){threw=false;try{if("businessType" in invalid)buildConsultationRequest(invalid);else buildServiceInquiryRequest(invalid)}catch(e){threw=e instanceof LeadContractError}equal(threw,true)}
const canonical=buildContactRequest({name:"A",email:"a@b.co",message:"M",language:"me",utm_source:"x",unknown:"x"});equal("utm_source" in canonical,false);
let url="";globalThis.fetch=async(input)=>{url=String(input);return new Response("{}",{status:200})};await submitLeadTo("https://api.example///","/api/contact",{});equal(url,"https://api.example/api/contact");
globalThis.fetch=async()=>new Response(JSON.stringify({error:{fields:{email:"invalid"}}}),{status:422});await rejects(()=>submitLeadTo("https://api.example","/api/contact",{}),e=>e instanceof LeadSubmissionError&&e.kind==="validation"&&e.fields.email==="invalid");
for(const [status,kind] of [[429,"rate_limit"],[500,"server"]] as const){globalThis.fetch=async()=>new Response("",{status});await rejects(()=>submitLeadTo("https://api.example","/api/contact",{}),e=>e instanceof LeadSubmissionError&&e.kind===kind)}
globalThis.fetch=async()=>{throw new TypeError("offline")};await rejects(()=>submitLeadTo("https://api.example","/api/contact",{}),e=>e instanceof LeadSubmissionError&&e.kind==="network");
globalThis.fetch=async(_input,init)=>new Promise((_resolve,reject)=>init?.signal?.addEventListener("abort",()=>reject(new DOMException("Aborted","AbortError"))));await rejects(()=>submitLeadTo("https://api.example","/api/contact",{},1),e=>e instanceof LeadSubmissionError&&e.kind==="timeout");
console.log("Lead contract tests passed");
